tenant:
  username: ""
  password: ""
  scenario: 3          # which scenario to deploy (2-7)
aap:
  version: "2.6"
  operatorChannel: stable-2.6
  controller:
    enabled: true
  eda:
    enabled: true
  hub:
    enabled: false                                          # override to true in AgV for scenarios that need Hub
    fileStorageSize: 10Gi
    fileStorageAccessMode: ReadWriteMany
    fileStorageClass: ocs-external-storagecluster-cephfs   # CephFS required for RWX
